#  Write a program to input eight s from the user and display all the unique s (once).
s = set()
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
n = (input('Give the Number: '))
s.add(int(n))
print(s)
